services:
  postgres:
    container_name: sakujj_postgres_clever_bank
    build: .
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - sakujj_pg_data_clever_bank:/var/lib/postgresql/data

  postgres-test:
    container_name: sakujj_postgres_clever_bank_test
    build:
      dockerfile: ./Dockerfile-test
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - sakujj_pg_data_clever_bank_test:/var/lib/postgresql/data

volumes:
  sakujj_pg_data_clever_bank:
  sakujj_pg_data_clever_bank_test:
